### PR TITLE
adding spinkube

### PR DESCRIPTION
**Pull request by asteurer**
Closes https://github.com/kairos-io/kairos/issues/635

### CODE REVIEW

**Comment by asteurer** [comment]
This was tested on the following distros:
#### Success
- Ubuntu 24.04
- Fedora 40

### Fail
- Alpine 3.19 (needs `systemd`)

**Review by mauromorales — APPROVED** [review]
Fantastic, thanks!

**Comment by asteurer** [comment]
@Itxaka It's an issue with the Kwasm installer: https://github.com/search?q=repo%3AKWasm%2Fkwasm-node-installer%20systemctl&type=code

**Comment by asteurer** [comment]
Also, @mauromorales do I need to do anything specific to get the `spinkube` bundle on to [Quay](https://quay.io/repository/kairos/community-bundles?tab=tags)?

**Pull request merged**
